name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: | 
          3.1.x
          6.0.x

    - name: Build service
      run: dotnet build src/chancies.server.sln --configuration Release -o ${{env.DOTNET_ROOT}}/output
