# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Release

on:
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: chancies.server   # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './src'   # set this to the path to your web app project, defaults to the repository root

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: | 
          3.1.x
          6.0.x

    - name: Build
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build chancies.server.sln --configuration Release -o ./output
        popd

    - name: 'Deploy'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
    # - name: Upload server artifact
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: personalweb-server
    #     path: ${{env.DOTNET_ROOT}}/output

  # deploy:
    
    # runs-on: windows-latest
    # needs: build
    # environment:
    #   name: 'production'
    #   url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    # steps:
    # - name: Download artifact from build job
    #   uses: actions/download-artifact@v2
    #   with:
    #     name: personalweb-server

    # - name: Deploy to Azure Web App
    #   id: deploy-to-webapp
    #   uses: azure/webapps-deploy@v2
    #   with:
    #     app-name: 'personalweb-uks-app'
    #     publish-profile: ${{ secrets.APPSERVICE_PUBLISH_PROFILE }}
    #     package: .